# -*- coding: utf-8 -*-
"""01_corpus_exploration.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rZn4vDp0ANlvvufU-14Vr2wSEBGyHGTx

# 01 — Corpus exploration

## Goal

This notebook explores the structure of the Corpus Chapitres before any preprocessing is performed. It identifies the corpus organisation, inspects the XML structure, extracts bibliographic metadata, performs basic quality control, and generates descriptive statistics used in Chapter 3.

No modifications are made to the original XML files.
"""

from google.colab import drive
drive.mount("/content/drive")

"""## 2. Project organisation"""

from pathlib import Path

PROJECT_DIR = Path("/content/drive/MyDrive/SemanticChangeThesis")

DATA_DIR = PROJECT_DIR / "data"
RAW_DIR = DATA_DIR / "raw"
METADATA_DIR = DATA_DIR / "metadata"
PROCESSED_DIR = DATA_DIR / "processed"

RESULTS_DIR = PROJECT_DIR / "results"
TABLES_DIR = RESULTS_DIR / "tables"
FIGURES_DIR = RESULTS_DIR / "figures"

NOTEBOOKS_DIR = PROJECT_DIR / "notebooks"
SCRIPTS_DIR = PROJECT_DIR / "scripts"
MODELS_DIR = PROJECT_DIR / "models"

for folder in [
    RAW_DIR,
    METADATA_DIR,
    PROCESSED_DIR,
    TABLES_DIR,
    FIGURES_DIR,
    NOTEBOOKS_DIR,
    SCRIPTS_DIR,
    MODELS_DIR,
]:
    folder.mkdir(parents=True, exist_ok=True)

print("Project folders ready.")
print(PROJECT_DIR)

"""## 3. Locating the corpus"""

print("Files in raw folder:")
for file in RAW_DIR.iterdir():
    print(file.name)

corpus_folder = RAW_DIR / "ANRChapitres-2000romans19e20e-ea770e4"

xml_files = sorted(corpus_folder.glob("*.xml"))

print(f"Number of XML files: {len(xml_files)}")
print("\nFirst five files:\n")

for file in xml_files[:5]:
    print(file.name)

"""## 4. Inspecting the XML structure

Before extracting metadata automatically, several XML files are inspected to verify that the corpus follows a consistent TEI-XML structure.
"""

with open(xml_files[0], "r", encoding="utf-8") as f:
    for _ in range(80):
        print(f.readline(), end="")

"""## 5. Metadata extraction

The metadata are extracted from the TEI header of each XML file. The extracted fields include the file name, title, author, author birth and death dates, author sex, publication year, and available genre labels.
"""

import re
import pandas as pd
from tqdm.auto import tqdm

def read_header_only(xml_path, max_chars=20000):
    with open(xml_path, "r", encoding="utf-8") as f:
        text = f.read(max_chars)

    if "</teiHeader>" in text:
        text = text.split("</teiHeader>")[0] + "</teiHeader>"

    return text

def extract_metadata_fast(xml_path):
    header = read_header_only(xml_path)

    def find(pattern):
        match = re.search(pattern, header, flags=re.DOTALL)
        return match.group(1).strip() if match else None

    title = find(r"<title>(.*?)</title>")
    author = find(r'<author[^>]*name="([^"]*)"')
    author_birth = find(r'<author[^>]*from="([^"]*)"')
    author_death = find(r'<author[^>]*to="([^"]*)"')
    author_sex = find(r'<author[^>]*sex="([^"]*)"')
    publication_year = find(r'<date[^>]*type="created"[^>]*when="([^"]*)"')

    terms = re.findall(r"<term>(.*?)</term>", header, flags=re.DOTALL)
    terms = [t.strip() for t in terms]

    return {
        "file": xml_path.name,
        "title": title,
        "author": author,
        "author_birth": author_birth,
        "author_death": author_death,
        "author_sex": author_sex,
        "publication_year": publication_year,
        "genres": "; ".join(terms) if terms else None,
    }

metadata = [extract_metadata_fast(path) for path in tqdm(xml_files)]
metadata_df = pd.DataFrame(metadata)

metadata_df.to_csv(METADATA_DIR / "metadata_raw.csv", index=False, encoding="utf-8")

metadata_df.head()

"""## 6. Metadata validation and quality control

The extracted metadata are checked before being used for temporal segmentation. The raw publication year is preserved, and corrected values are stored separately to maintain an audit trail.
"""

metadata_df.info()

metadata_quality = pd.DataFrame({
    "field": ["file", "title", "author", "author_birth", "author_death", "author_sex", "publication_year", "genres"],
    "missing_values": [
        metadata_df["file"].isna().sum(),
        metadata_df["title"].isna().sum(),
        metadata_df["author"].isna().sum(),
        metadata_df["author_birth"].isna().sum(),
        metadata_df["author_death"].isna().sum(),
        metadata_df["author_sex"].isna().sum(),
        metadata_df["publication_year"].isna().sum(),
        metadata_df["genres"].isna().sum(),
    ],
    "available_values": [
        metadata_df["file"].notna().sum(),
        metadata_df["title"].notna().sum(),
        metadata_df["author"].notna().sum(),
        metadata_df["author_birth"].notna().sum(),
        metadata_df["author_death"].notna().sum(),
        metadata_df["author_sex"].notna().sum(),
        metadata_df["publication_year"].notna().sum(),
        metadata_df["genres"].notna().sum(),
    ],
})

metadata_quality.to_csv(TABLES_DIR / "metadata_quality.csv", index=False, encoding="utf-8")
metadata_quality

metadata_df["publication_year_raw"] = metadata_df["publication_year"]
metadata_df["publication_year_corrected"] = metadata_df["publication_year"]
metadata_df["date_correction_note"] = ""

"""A small number of publication years were found to be incorrect in the TEI metadata. These were corrected manually after verification. The original values are preserved in `publication_year_raw`, while the corrected values are stored in `publication_year_corrected`."""

manual_date_corrections = {
    "1838_Gautier-Theophile_Fortunio.xml": 1838,
    "1860_Vie-Anduze-Henri_Dernier-amour-de-Cinq-Mars-roman-historique.xml": 1860,
    "1910_Ivoi-Paul-d-_Millionnaire-malgre-lui_tome-2.xml": 1910,
    "1935_Delly_Contes.xml": 1935
}

for filename, correct_year in manual_date_corrections.items():
    mask = metadata_df["file"] == filename
    metadata_df.loc[mask, "publication_year_corrected"] = correct_year
    metadata_df.loc[mask, "date_correction_note"] = "Corrected manually after metadata validation"

metadata_df[metadata_df["date_correction_note"] != ""]

metadata_audit = metadata_df.copy()

metadata_final = metadata_df.copy()
metadata_final["publication_year"] = metadata_final["publication_year_corrected"]

columns_to_keep = [
    "file",
    "title",
    "author",
    "author_birth",
    "author_death",
    "author_sex",
    "publication_year",
    "genres",
]

metadata_final = metadata_final[columns_to_keep]

metadata_audit.to_csv(METADATA_DIR / "metadata_audit.csv", index=False, encoding="utf-8")
metadata_final.to_csv(METADATA_DIR / "metadata.csv", index=False, encoding="utf-8")


metadata_final.head()

"""## 7. Corpus statistics

The following statistics are computed from the validated metadata table.
"""

metadata_final["publication_year"] = pd.to_numeric(
    metadata_final["publication_year"],
    errors="coerce"
).astype("Int64")

all_genres = (
    metadata_final["genres"]
    .dropna()
    .str.split(";")
    .explode()
    .str.strip()
)

corpus_stats = pd.DataFrame({
    "statistic": [
        "Number of XML files",
        "Number of unique authors",
        "Earliest publication year",
        "Latest publication year",
        "Number of unique genre labels",
        "Missing publication years",
        "Missing authors",
        "Manually corrected publication years",
    ],
    "value": [
        len(metadata_final),
        metadata_final["author"].nunique(dropna=True),
        int(metadata_final["publication_year"].min()),
        int(metadata_final["publication_year"].max()),
        all_genres.nunique(),
        metadata_final["publication_year"].isna().sum(),
        metadata_final["author"].isna().sum(),
        (metadata_audit["date_correction_note"] != "").sum(),
    ],
})

corpus_stats.to_csv(TABLES_DIR / "corpus_statistics.csv", index=False, encoding="utf-8")
corpus_stats

"""## 8. Temporal Distribution

The corpus is grouped by publication decade in order to assess whether decade-level temporal segmentation is suitable for the diachronic analysis.
"""

metadata_final["decade"] = (
    metadata_final["publication_year"] // 10 * 10
).astype("Int64")

novels_per_decade = (
    metadata_final
    .dropna(subset=["decade"])
    .groupby("decade")
    .size()
    .reset_index(name="number_of_novels")
    .sort_values("decade")
)

novels_per_decade.to_csv(TABLES_DIR / "novels_per_decade.csv", index=False, encoding="utf-8")
novels_per_decade

authors_per_decade = (
    metadata_final
    .dropna(subset=["decade"])
    .groupby("decade")["author"]
    .nunique()
    .reset_index(name="number_of_authors")
    .sort_values("decade")
)

authors_per_decade.to_csv(TABLES_DIR / "authors_per_decade.csv", index=False, encoding="utf-8")
authors_per_decade

import matplotlib.pyplot as plt

plt.figure(figsize=(12, 6))

plt.bar(
    novels_per_decade["decade"].astype(str),
    novels_per_decade["number_of_novels"]
)

plt.xticks(rotation=45)
plt.xlabel("Publication decade")
plt.ylabel("Number of novels")
plt.title("Number of novels by publication decade")

plt.tight_layout()

plt.savefig(FIGURES_DIR / "novels_per_decade.png", dpi=300, bbox_inches="tight")

plt.show()

"""## 9. Genre metadata

Genre annotations are not available for all works. The following statistics therefore describe only the annotated subset and should not be interpreted as a complete genre distribution for the entire corpus.
"""

genre_summary = pd.DataFrame({
    "Category": [
        "Annotated with at least one genre",
        "No genre annotation",
    ],
    "Count": [
        metadata_final["genres"].notna().sum(),
        metadata_final["genres"].isna().sum(),
    ],
})

genre_summary["Percentage"] = (
    genre_summary["Count"] / len(metadata_final) * 100
).round(2)

genre_summary.to_csv(TABLES_DIR / "genre_metadata_summary.csv", index=False, encoding="utf-8")
genre_summary

genre_labels = (
    metadata_final["genres"]
    .dropna()
    .str.split(";")
    .explode()
    .astype(str)
    .str.strip()
)
# Standardise "nouvelle" and "nouvelles"
genre_labels = genre_labels.replace({
    "nouvelle": "nouvelles"
})

# Remove empty labels and labels that are only quotes
genre_labels = genre_labels[
    (genre_labels != "") &
    (genre_labels != '""') &
    (genre_labels != "''")
]

genre_counts = (
    genre_labels
    .value_counts()
    .reset_index()
)

genre_counts.columns = ["genre", "count"]

genre_counts.to_csv(TABLES_DIR / "genre_counts.csv", index=False, encoding="utf-8")

genre_counts.head(20)

genre_labels = (
    metadata_final["genres"]
    .dropna()
    .str.split(";")
    .explode()
    .astype(str)
    .str.strip()
)

sorted(genre_labels.unique())

top10_genres = genre_counts.head(10)

plt.figure(figsize=(10, 6))

plt.barh(
    top10_genres["genre"],
    top10_genres["count"]
)

plt.gca().invert_yaxis()

plt.xlabel("Number of annotated works")
plt.title("Most frequent genre labels among annotated works")

plt.tight_layout()

plt.savefig(FIGURES_DIR / "top_genres.png", dpi=300, bbox_inches="tight")

plt.show()

sorted(genre_labels.unique())

"""## 10. Conclusions

This notebook explored the structure of the *Corpus Chapitres* and extracted the bibliographic metadata required for the remainder of the thesis.

The corpus consists of TEI-encoded XML files. Metadata extraction identified publication dates, authors, author information, and available genre labels. A quality-control stage was used to identify and correct a small number of erroneous publication years while preserving the raw values for transparency.

The resulting metadata tables and descriptive statistics provide the basis for the preprocessing pipeline implemented in the following notebook and for the corpus description presented in Chapter 3.

## Files generated

This notebook generates the following files:

### Metadata

- `data/metadata/metadata_raw.csv`
- `data/metadata/metadata_audit.csv`
- `data/metadata/metadata.csv`

### Tables

- `results/tables/metadata_quality.csv`
- `results/tables/corpus_statistics.csv`
- `results/tables/novels_per_decade.csv`
- `results/tables/authors_per_decade.csv`
- `results/tables/genre_metadata_summary.csv`
- `results/tables/genre_counts.csv`

### Figures

- `results/figures/novels_per_decade.png`
- `results/figures/top_genres.png`
"""